#Second Question
#Guessing game
#Damascus on 04/17/2023
#The gamer has five tries to guess the random number generated by the computer.

#first import the random library
import random


#print a massage to the gamer that the computer is guseeing a number and explain the game to him
print("I will guess a number between 1 and 20 and you will have to guess the number in order to win\n\
I will give you five chances to guess it and will give you a litile hint if you are above or below it.\nGood Luck!\n")


#generate a random number between 1 and 20 and assigne te vale to the variable "target"
target = random.randint(1,20)

#prnt a message indicating the start of the game
print("The game is started\n")



#a string array that will be used to loop over it and show the guessing order. 
chances = ["first","second","thrird","fourth","fifth"]

#bulid a loop that gives the user five tries to gues the generated number.
for i in chances:
    guessedNumber = input("\nEnter your {} geuss : ".format(i)) #let the user enter his guess

    try: #check if the user has enter a number
        guessedNumber = int(guessedNumber)
    except:
        print("you didn't enter a number!")# if the user didn't enter a numbe a message will apear and the game will continue.
        continue

    if guessedNumber == target: #check if the guess was correct
        print("Wow you WON, it's {}".format(target)) #if his guess was correct print a massege that the user won and break the loop
        break 

    if i == "fifth" : #check if the this was the last chance
        print("You LOST the targeted numbeer was {}".format(target)) #if this was his last chance print a meesage telling him that he lost and break
        break

    if guessedNumber > target: #check if the user has entered a number above the targeted value
        print ("Try again. your guess was ABOVE the targeted number")

    elif guessedNumber < target: #check if the user has entered a number below the targeted value
        print ("Try again. your guess was BELOW the targeted number")
    